import numpy as np
a= np.array([2,3,4])
print (a)
print(a.dtype)
b=np.array([1.2,3.5,5.1])
print(b)
print(b.dtype)
c=np.array([(1.5,2,3),(4,5,6)])
print(c)
d=np.array([[1,2],[3,4]],dtype=complex)
print(d)
print(d.dtype)
